#!/bin/bash
TENANT="00000000-0000-0000-0000-000000000001"
echo "=== Testing All APIs ==="
echo "1. Chart of Accounts:"
curl -s "http://localhost:3001/chart-of-accounts?tenant_id=$TENANT" > /dev/null && echo "OK" || echo "FAIL"
echo "2. Vendors:"
curl -s "http://localhost:3003/vendors?tenant_id=$TENANT" > /dev/null && echo "OK" || echo "FAIL"
echo "3. Customers:"
curl -s "http://localhost:3004/customers?tenant_id=$TENANT" > /dev/null && echo "OK" || echo "FAIL"
echo "4. Bank Accounts:"
curl -s "http://localhost:3005/bank-accounts?tenant_id=$TENANT" > /dev/null && echo "OK" || echo "FAIL"
echo "5. Journal Entries:"
curl -s "http://localhost:3001/events/by-tenant/$TENANT?eventType=JournalEntryPosted" > /dev/null && echo "OK" || echo "FAIL"
echo "6. Trial Balance:"
curl -s "http://localhost:3008/reports/trial-balance?tenant_id=$TENANT" > /dev/null && echo "OK" || echo "FAIL"
echo "7. Income Statement:"
curl -s "http://localhost:3008/reports/income-statement?tenant_id=$TENANT&start_date=2025-01-01&end_date=2025-12-31" > /dev/null && echo "OK" || echo "FAIL"
