apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "15s"

  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: airp_master
    user: airp_admin
    secureJsonData:
      password: airp_secure_2024
    jsonData:
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 5
      connMaxLifetime: 14400
    editable: true
